// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCZhptvnfF7SwodxmwvUxL4P19mZChx-Q',
    appId: '1:214775796008:web:f84f085978bbdb1959c01d',
    messagingSenderId: '214775796008',
    projectId: 'ite124-auth-demo-be703',
    authDomain: 'ite124-auth-demo-be703.firebaseapp.com',
    storageBucket: 'ite124-auth-demo-be703.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBArf9MO2ZAV_tSofmwj11-nLa9bSTv0TA',
    appId: '1:214775796008:android:6c4acbdbc2733d1a59c01d',
    messagingSenderId: '214775796008',
    projectId: 'ite124-auth-demo-be703',
    storageBucket: 'ite124-auth-demo-be703.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTvzGeSnIv9Brx15P2j0Wr2fS9X5LB2OU',
    appId: '1:214775796008:ios:cfbb8435caafa81b59c01d',
    messagingSenderId: '214775796008',
    projectId: 'ite124-auth-demo-be703',
    storageBucket: 'ite124-auth-demo-be703.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTvzGeSnIv9Brx15P2j0Wr2fS9X5LB2OU',
    appId: '1:214775796008:ios:cfbb8435caafa81b59c01d',
    messagingSenderId: '214775796008',
    projectId: 'ite124-auth-demo-be703',
    storageBucket: 'ite124-auth-demo-be703.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCZhptvnfF7SwodxmwvUxL4P19mZChx-Q',
    appId: '1:214775796008:web:0eee3de31665d10f59c01d',
    messagingSenderId: '214775796008',
    projectId: 'ite124-auth-demo-be703',
    authDomain: 'ite124-auth-demo-be703.firebaseapp.com',
    storageBucket: 'ite124-auth-demo-be703.firebasestorage.app',
  );
}
